In [ ]:
# Project :
# Let us build a complete project using NumPy (without any help).

# Path: project_data = 'KAG_Conversion_Data.csv'
# Features:
# ad_id: unique ID for each ad

# xyzcampaignid: an ID associated with each ad campaign of XYZ company

# fbcampaignid: an ID associated with how Facebook tracks each campaign

# age: age of the person to whom the ad is shown

# gender: gender of the person to whom the add is shown

# interest: a code specifying the category to which the person’s 
# interest belongs (interests are as mentioned in the person’s Facebook public profile)

# Impressions: the number of times the ad was shown

# Clicks: number of clicks on for that ad

# Spent: Amount paid by company xyz to Facebook, to show that ad

# Total conversion: Total number of people who enquired about the product after seeing the ad

# Approved conversion: Total number of people who bought the product after seeing the ad


# Instructions:
# A) Load the data. Data is already given to you in variable path

# B)How many unique ad campaigns (xyzcampaignid) does this data contain ? 
# And for how many times was each campaign run ?

# C) What are the age groups that were targeted through these ad campaigns?

# D)What was the average, minimum and maximum amount spent on the ads?

# E) What is the id of the ad having the maximum number of clicks ?

# F) How many people bought the product after seeing the ad with most clicks? 
# Is that the maximum number of purchases in this dataset?

# G) So the ad with the most clicks didn't fetch the maximum number of purchases. 
# Find the details of the product having maximum number of purchases

In [ ]:
# A) Load the data. Data is already given to you in variable path
import numpy as np
data_file = "KAG_Conversion_Data.csv"

In [ ]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1, dtype= int)
data = np.genfromtxt(data_file, delimiter=",", skip_header=1, dtype= str)
# data = data.astype()
print("\nData: \n\n", data)


Data: 

 [['708746' '916' '103916' ... '1.429999948' '2' '1']
 ['708749' '916' '103917' ... '1.820000023' '2' '0']
 ['708771' '916' '103920' ... '0' '1' '0']
 ...
 ['1314412' '1178' '179979' ... '40.28999949' '2' '0']
 ['1314414' '1178' '179981' ... '198.7100005' '8' '2']
 ['1314415' '1178' '179982' ... '165.6099987' '5' '2']]


In [ ]:
xyz = data[:,1]
print(xyz) 

['916' '916' '916' ... '1178' '1178' '1178']


In [ ]:
# B) How many unique ad campaigns (xyzcampaignid) does this data contain ? 
# And for how many times was each campaign run ?

np.unique(xyz, return_counts=True)   
# use return_counts to get all values 
# where unique

(array(['1178', '916', '936'], dtype='<U11'), array([625,  54, 464]))

In [ ]:
# C) What are the age groups that were targeted through these ad campaigns?

AgeTarget = data[:,3]
print(AgeTarget)
np.unique(AgeTarget, return_counts= True) #, return_index=True)

['30-34' '30-34' '30-34' ... '45-49' '45-49' '45-49']


(array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11'),
 array([426, 248, 210, 259]))

In [ ]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1, dtype= float)

print(data)

[[7.08746000e+05 9.16000000e+02 1.03916000e+05 ... 1.42999995e+00
  2.00000000e+00 1.00000000e+00]
 [7.08749000e+05 9.16000000e+02 1.03917000e+05 ... 1.82000002e+00
  2.00000000e+00 0.00000000e+00]
 [7.08771000e+05 9.16000000e+02 1.03920000e+05 ... 0.00000000e+00
  1.00000000e+00 0.00000000e+00]
 ...
 [1.31441200e+06 1.17800000e+03 1.79979000e+05 ... 4.02899995e+01
  2.00000000e+00 0.00000000e+00]
 [1.31441400e+06 1.17800000e+03 1.79981000e+05 ... 1.98710001e+02
  8.00000000e+00 2.00000000e+00]
 [1.31441500e+06 1.17800000e+03 1.79982000e+05 ... 1.65609999e+02
  5.00000000e+00 2.00000000e+00]]


In [ ]:
# D) What was the average, minimum and maximum amount spent on the ads?


data = np.genfromtxt(data_file, delimiter=",", skip_header=1, dtype= float)
Avg = np.mean(data[:,8])
MINIMUM  = np.min(data[:,8])
MAXIMUM = np.max(data[:,8])
print(Avg)
print(MAXIMUM)
print(MINIMUM)

51.36065613141295
639.9499981
0.0


In [ ]:
# Max_Clicks = np.max(data[:7])
# print(Max_Clicks)

In [ ]:

spent = np.mean(data[:,8].astype('float64'))
print(spent)

51.36065613141295


In [ ]:
# E) What is the id of the ad having the maximum number of clicks ?
np.max(data[:,7])

421.0

In [ ]:
# F) How many people bought the product after seeing the ad with most clicks? 
# Is that the maximum number of purchases in this dataset?

np.where(data[:,7] == 421)
maxof = np.where(data == np.max(data[:,7]))
print(maxof)

data[maxof[0], 0]

(array([860]), array([7]))


array([1121814.])

In [ ]:
# F) How many people bought the product after seeing the ad with most clicks? 
# Is that the maximum number of purchases in this dataset? ALTERNATIVE WAY
ID_max = data[data[:,7] == 421].astype(int)
print(ID_max[0,0])
print(ID_max[:,:])

1121814
[[             1121814                 1178               144659
  -9223372036854775808 -9223372036854775808                   27
               2223278                  421                  612
                    38                   13]]


In [ ]:
# z = np.where(data == np.max(data[:,7]))
# data[z[0],0]

In [ ]:
# G) How many people bought the product after seeing the ad with most clicks? 
# Is that the maximum number of purchases in this dataset?
#  ALTERNATIVE WAY
data[860,10]

13.0

In [ ]:
# Is that the maximum number of purchases in this dataset?
np.max(data[:,10])

21.0

In [ ]:
# So the ad with the most clicks didn't fetch the maximum number of purchases. 
# Find the details of the product having maximum number of purchases

np.unique(data[data[:,10]== 13]).astype(int)

array([                  13,                   27,                   38,
                        421,                  612,                 1178,
                     144659,              1121814,              2223278,
       -9223372036854775808, -9223372036854775808])

In [ ]:
max_Number_of_Purchases = data[data[:,10]==21].astype(int)
print(max_Number_of_Purchases)

[[             1121104                 1178               144533
  -9223372036854775808 -9223372036854775808                   16
               2080666                  202                  360
                    40                   21]]


In [ ]:
max_Number_of_Purchases

array([[             1121104,                 1178,               144533,
        -9223372036854775808, -9223372036854775808,                   16,
                     2080666,                  202,                  360,
                          40,                   21]])

In [ ]:
print("The Ad id for the product having maximum number of purchases: ", max_Number_of_Purchases[0][0])

The Ad id for the product having maximum number of purchases:  1121104


In [ ]:
data_string = np.genfromtxt(data_file, delimiter=",", skip_header=1, dtype= str)
max_Number_of_purchases_str = data_string[528,:]
print(max_Number_of_purchases_str)
# max_Number_of_Purchases_string = data_string[data_string[:,10]==21]
# print(max_Number_of_Purchases_string[528, :])

['1121104' '1178' '144533' '30-34' 'M' '16' '2080666' '202' '360.1500015'
 '40' '21']


In [ ]:
np.where(data[:,0]==1121104)

(array([528]),)

In [ ]:
max_purchases_index = np.where(data == np.max(data[:,10]))
data[max_purchases_index[0][0]]

array([7.10360000e+05, 9.16000000e+02, 1.04185000e+05,            nan,
                  nan, 2.10000000e+01, 2.18200000e+03, 1.00000000e+00,
       1.52999997e+00, 1.00000000e+00, 1.00000000e+00])

In [ ]:
print("The Ad id for the product having maximum number of purchases: ", max_Number_of_Purchases[0][0])
print("The ")

The Ad id for the product having maximum number of purchases:  1121104
The 


In [ ]:
dictionary = {"ad_id":max_Number_of_Purchases[0][0], 
              "xyz_campaign_id":max_Number_of_Purchases[0][1],
              "fb_campaign_id":max_Number_of_Purchases[0][2],
              "age":max_Number_of_purchases_str[3],
              "gender":max_Number_of_purchases_str[4],
              "interest":max_Number_of_Purchases[0][5], 
              "Impressions":max_Number_of_Purchases[0][6],
              "Clicks":max_Number_of_Purchases[0][7],
              "Spent":max_Number_of_Purchases[0][8],
              "Total_Conversion":max_Number_of_Purchases[0][9],
              "Approved_Conversion":max_Number_of_Purchases[0][10]}
              	

In [ ]:
print(dictionary)

{'ad_id': 1121104, 'xyz_campaign_id': 1178, 'fb_campaign_id': 144533, 'age': '30-34', 'gender': 'M', 'interest': 16, 'Impressions': 2080666, 'Clicks': 202, 'Spent': 360, 'Total_Conversion': 40, 'Approved_Conversion': 21}
